### ISSUE TITLE
Potential Disk IO Bottleneck

### ISSUE THREAD

**Issue by izu-stanley** [somT-oss/kuda-assistant#3]
https://github.com/somT-oss/kuda-assistant/blob/daafe45bf4c7c8162d2bb910f864a08b05582587/src/main.py#L192

At scale, writing every email file to disk could put a strain on disk which could cause it to fail. Looking at the current structure of the application, state is maintained in the application itself and a lot of info is persisted locally. If disk failure happens, all of that data is lost - which would impact your analysis

**Comment by somT-oss** [comment]
i have updated the storage to use mongodb atlas.
